version: '2.1'
services:
  pets_db:
    container_name: pets_db
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_USER=pet_user
      - POSTGRES_PASSWORD=pet_password
      - POSTGRES_DB=pets
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 20s
      retries: 4